### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by juanpenia** [juanpenia/ScrabbleAR#78]
- [x] preguntar nombre del jugador al iniciar una partida o menu principal

- [x] verificar en el primer turno que la primera palabra este en la casilla principal (hecho solo cuando le toca al jugador, falta cpu)

- [x] hacer que las palabras solo sean validas cuando las letras estan unidas

- [x] realizar la funcionalidad de pasar turno

- [x] que al cambiar fichas, se pase el turno automaticamente

- [x] actualizar jugadas al hacer una (ya sea jugador o computadora)

- [x] agregar sfx y musica de ambiente (falta terminar)

- [x] hacer que no se puedan superponer fichas pues ta mal (bug)

- [x] verificar que las palabras que pone el jugador sean de dos letras al menos

- [x] realizar terminar_juego()

- [x] realizar la funcionalidad de posponer partida

- [x] arreglar bug que se puede poner letra atras y rompe todo (al menos en horizontal)

- [x] hacer que no se pueda hacer que haya fichas con cant = 0

- [x] editar el top 10 para ver tambien por dificultades? (no es para nada una prioridad)

- [x] acomodar el codigo en modulos una vez terminado
